/*
 * Power control block
 *
 * This API was created to monitor states of Power Control Block and send some commands to it.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	"os"
	"time"

	"./control"
	"github.com/natefinch/lumberjack"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//

	sw "./go"
)

var errLog *log.Logger

func main() {
	f, errf := os.OpenFile("output.log", os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
	if errf != nil {
		log.Fatalf("Error open log file: %v", errf)
	}
	defer f.Close()
	errLog = log.New(f, "", log.Ldate|log.Ltime)
	errLog.SetOutput(&lumberjack.Logger{
		Filename:   "output.log",
		MaxSize:    2,  // megabytes after which new file is created
		MaxBackups: 10, // number of backups
		MaxAge:     28, // days
	})

	log.Printf("Hello programm")

	time.Sleep(time.Second)
	control.InitProtocol()
	err := control.ProcStart()
	if err != nil {
		log.Println(err)
	}

	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
