/*
 * Power control block
 *
 * This API was created to monitor states of Power Control Block and send some commands to it.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
)

func GetPwrBat(w http.ResponseWriter, r *http.Request) {
	var battery RespBattery
	battery.Results = 94
	battery.Status = "OK"
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, "Оооой-ой рияри-ооой батарейка!\n")
	fmt.Fprintf(w, "Заряд: %d\n", battery.Results)
	fmt.Fprintf(w, "%s\n", battery.Status)
}
