/*
 * Power control block
 *
 * This API was created to monitor states of Power Control Block and send some commands to it.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"

	"../com"
)

func GetPwrWiFi(w http.ResponseWriter, r *http.Request) {
	com.Send([]byte("GetPwrWiFi"))
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func SetPwrWiFi(w http.ResponseWriter, r *http.Request) {
	com.Send([]byte("SetPwrWiFi"))
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
