/*
 * Power control block
 *
 * This API was created to monitor states of Power Control Block and send some commands to it.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"SetButtonsLock",
		strings.ToUpper("Post"),
		"/buttons/lock",
		SetButtonsLock,
	},

	Route{
		"GetFileConfig",
		strings.ToUpper("Get"),
		"/files/get/config",
		GetFileConfig,
	},

	Route{
		"GetFilePhones",
		strings.ToUpper("Get"),
		"/files/get/phones",
		GetFilePhones,
	},

	Route{
		"SetFileConfig",
		strings.ToUpper("Post"),
		"/files/set/config",
		SetFileConfig,
	},

	Route{
		"SetFileNPhones",
		strings.ToUpper("Post"),
		"/files/set/phones",
		SetFileNPhones,
	},

	Route{
		"GetModemConnByID",
		strings.ToUpper("Get"),
		"/modem/get/conn",
		GetModemConnByID,
	},

	Route{
		"GetModemFlyByID",
		strings.ToUpper("Get"),
		"/modem/get/state/flymode",
		GetModemFlyByID,
	},

	Route{
		"GetModemImeiByID",
		strings.ToUpper("Get"),
		"/modem/get/state/imei",
		GetModemImeiByID,
	},

	Route{
		"GetModemSimByID",
		strings.ToUpper("Get"),
		"/modem/get/state/sim",
		GetModemSimByID,
	},

	Route{
		"GetModemStByID",
		strings.ToUpper("Get"),
		"/modem/get/state",
		GetModemStByID,
	},

	Route{
		"SetModemFlyByID",
		strings.ToUpper("Post"),
		"/modem/set/state/flymode",
		SetModemFlyByID,
	},

	Route{
		"SetModemImeiByID",
		strings.ToUpper("Post"),
		"/modem/set/state/imei",
		SetModemImeiByID,
	},

	Route{
		"SetModemSimByID",
		strings.ToUpper("Post"),
		"/modem/set/state/sim",
		SetModemSimByID,
	},

	Route{
		"GetPwrCfg",
		strings.ToUpper("Get"),
		"/power/get",
		GetPwrCfg,
	},

	Route{
		"SetDownPwrPC",
		strings.ToUpper("Post"),
		"/power/set/pc",
		SetDownPwrPC,
	},

	Route{
		"SetPwrCfg",
		strings.ToUpper("Post"),
		"/power/set",
		SetPwrCfg,
	},

	Route{
		"SetPwrModemByID",
		strings.ToUpper("Post"),
		"/power/set/modem",
		SetPwrModemByID,
	},

	Route{
		"SetPwrRelayByID",
		strings.ToUpper("Post"),
		"/power/set/relay",
		SetPwrRelayByID,
	},

	Route{
		"SetPwrWiFi",
		strings.ToUpper("Post"),
		"/power/set/wifi",
		SetPwrWiFi,
	},

	Route{
		"SetWaitmode",
		strings.ToUpper("Post"),
		"/power/set/waitmode",
		SetWaitmode,
	},

	Route{
		"GetSmsUnknown",
		strings.ToUpper("Get"),
		"/sms/unknown",
		GetSmsUnknown,
	},

	Route{
		"SetSendSms",
		strings.ToUpper("Post"),
		"/sms/send",
		SetSendSms,
	},

	Route{
		"SetSmsLock",
		strings.ToUpper("Post"),
		"/sms/lock",
		SetSmsLock,
	},
}
